CREATE DATABASE IF NOT EXISTS htql_svtt;

USE htql_svtt;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mssv VARCHAR(20) NOT NULL,
    hoten VARCHAR(100) NOT NULL,
    gioitinh INT NOT NULL,
    sdt VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    diachi VARCHAR(255) NOT NULL,
    malop VARCHAR(20) NOT NULL,
    khoa INT NOT NULL,
    nganh VARCHAR(50) NOT NULL,
    truong VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS dknhom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mssv VARCHAR(20) UNIQUE NOT NULL,
    nhom VARCHAR(10) NOT NULL,
    nguoihuongdan VARCHAR(100) NOT NULL,
    mota TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);